### ISSUE TITLE
Namespaced keywords in 0.1.2/Chrome Version 42.0.2311.90 (64-bit)

### ISSUE THREAD

**Issue by lgrapenthin** [binaryage/cljs-devtools#1]
Hi,
 unfortunately I can't try 0.2.0 because I don't have time to set up compiling Chrome myself and 0.2.0 doesn't work with aforementioned chrome version (I don't know how it relates to the revision / commit numbers in your README).

Thus I have to use 0.1.2. It works really great and is highly useful. 

The only problem is namespaced keywords not being displayed correctly. Only their name is shown.

Kind regards,
 Leon.

**Comment by darwin** [comment]
A side note: for 0.2.0 you can use this precompiled binary:
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/325000

(or find 325000 for your platform in other folders)

**Comment by lgrapenthin** [comment]
Thanks. I could reproduce the problem on later versions.

I guess this line https://github.com/binaryage/cljs-devtools/blob/master/src/devtools/format.cljs#L112 needs to be changed to

(keyword? value) (template span keyword-style (str value))
