### ISSUE TITLE
Anyway to check if this is available?

### ISSUE THREAD

**Issue by samedhi** [binaryage/cljs-devtools#10]
So this is very neat; however, it only works in a browser right? Is there a test I can run to determine whether we are running in a browser (as opposed to node or something else) so that I can only enable cljs-devtools in that event. Basically, in cljs, I want to use cljs-devtools if I am logging to a browser and I want to just use pr-str if I am not in a browser or am in a browser but not one that supports custom formatters.

**Comment by darwin** [comment]
More specifically this only works under Chrome 47+. Under other browsers, older Chrome or different platforms installation `:custom-formatters` feature of cljs-devtools does not have effect (you will get standard behaviour of `console.log`)

I think this is out of the scope of this project. I would recommend you to implement your own project-specific logging macros, which can detect platform and use appropriate logging tools.

**Comment by samedhi** [comment]
Sounds good. I just slightly dislike having "browser/version" only checks. Just wondering if there was something that checks if the functionality exist and then lets me enable or disable cljs-devtools. In the meantime, I will just do a browser test.

To be clear, the only reason I care is that I would like to use devtools on a browser that supports it if that is available, and EDN otherwise.

**Comment by darwin** [comment]
AFAIK there is no way how to detect if this is available.

So you would like a convenience function in the cljs-devtools which would return true for chrome 47+? And you would call this to decide if you want to do plain console.log or wrap your arguments in pr-str or something. That can be easily done. I thought you want me to add some logging layer which would do that work automatically.

**Comment by darwin** [comment]
In upcoming version you can call

```clojure
(feature-available? :custom-formatters)
```

It boils down to this call:
https://github.com/binaryage/cljs-devtools/blob/master/src/devtools/custom_formatters.cljs#L13-L14

**Comment by samedhi** [comment]
Hey darwin,

Really cool. I am working on a logging thing for work right now. I really appreciate being able to include cljs-devtools with a minimum of disruption to people who aren't using chrome.

Thanks you.
