### ISSUE TITLE
Check if custom formatters are enabled, and print warning if not

### ISSUE THREAD

**Issue by danielcompton** [binaryage/cljs-devtools#16]
If I am running Chrome in a fresh profile, I will sometimes forget to enable Custom Formatters and get confused for a bit when I see the raw JS objects being logged to the console. Is there any way for devtools to detect if custom formatters are enabled and print a big red warning if they aren't?

**Comment by darwin** [comment]
Hmm, I could set a test custom formatter. Then do `console.log` and detect if my handler was called. This way I could indirectly detect if custom formatters are enabled or not.

**Comment by darwin** [comment]
I realized the detection works only if console is closed. When you open console some time after printing the banner, this detection won't work.
