### ISSUE TITLE
false values not printed inside collections

### ISSUE THREAD

**Issue by danielcompton** [binaryage/cljs-devtools#24]
It seems like literal false values aren't printed by cljs-devtools inside collections. This happens from values entered at the Dirac REPL, and application values that are logged.

<img width="202" alt="screenshot of google chrome 8-08-16 4-01-58 pm" src="https://cloud.githubusercontent.com/assets/811954/17469022/721b187a-5d81-11e6-8818-209eec438222.png">

```
[binaryage/devtools "0.8.0"]
[binaryage/dirac "0.6.3"]
```

**Comment by darwin** [comment]
fixed in 895677e0da903249f297558f0192d8307d39d99b

**Comment by darwin** [comment]
[v0.8.1](https://github.com/binaryage/cljs-devtools/releases/tag/v0.8.1)
