### ISSUE TITLE
Allow to customize default formatters style

### ISSUE THREAD

**Issue by jeluard** [binaryage/cljs-devtools#3]
It would be nice to have some way to customize the style (color..) of default formatters.

**Comment by darwin** [comment]
I was planning to move all constants into a separate namespace, where they could be redefined.

No a big priority ATM. Pull requests welcome :)

**Comment by jeluard** [comment]
That sounds like a great solution.
I don't have much spare cycles now but I will add it to my list!

**Comment by darwin** [comment]
Implemented in v0.3.0:
https://github.com/binaryage/cljs-devtools/releases/tag/v0.3.0

**Comment by jeluard** [comment]
Cool thanks!
