### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by yogthos** [binaryage/cljs-devtools#31]
Currently, util tries to access `js/window` and this variable is not set on Node by default.

**Comment by darwin** [comment]
I'm not aware that custom formatters could work under node.js according to this doc, window object should be used:
https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/edit

But we could use goog.global instead of js/window and make it future-proof. I think.

**Comment by yogthos** [comment]
The use case I have is running node using the `--inspect` flag and connecting Chrome DevTools to the process. In theory, it should work the same as a browser based process.

**Comment by darwin** [comment]
I understand your goal. Custom formatters should work regardless of javascript context at hand.

AFAIK the custom formatters system wasn't really designed with node.js in mind. They look for `devtoolsFormatters` key presence under the window object. If they were aware of node.js they would do it in a different way.

Have you tried to implement a simple custom formatter under node.js? Or did you see anyone having one working?

**Comment by yogthos** [comment]
I haven't tried implementing one, and it definitely does look like Node wasn't considered in the custom formatter implementation. I'm mostly hoping that it could be worked around. :) Perhaps it would be possible to alias [global](https://nodejs.org/api/globals.html#globals_global) in node to `window`?

**Comment by darwin** [comment]
I just dug into chrome sources and found this:
https://github.com/v8/v8/blob/cd79924daba9061a2e8c8cb4fbb471268a3f1b9e/src/inspector/injected-script-source.js#L809

If `inspectedGlobalObject` is what we expect it to be. You might be right. And that is also what I was hoping for with using `goog.global`, which should be `window` in browser contexts and `global` in node.js context.

**Comment by yogthos** [comment]
👍 sounds promising :)

**Comment by darwin** [comment]
I won't have time to test this anytime soon. 

Feel free to go ahead and replace all js/window with goog.global to test this hypothesis. I would also accept a PR, of course.

**Comment by yogthos** [comment]
I'll take a look and let you know how it goes, I'll get a pr in if everything looks good.

**Comment by yogthos** [comment]
Good news, looks like switching to goog.global does the trick.

**Comment by darwin** [comment]
Merged. thanks!
