### ISSUE TITLE
Autocompletion for some reason is slow and jittery

### ISSUE THREAD

**Issue by agzam** [binaryage/cljs-devtools#33]
cljs-devtools is awesome, I can't thank you enough. This makes so many things better. However one thing still drives me nuts:

whenever I type something in Chrome Dev Console, the autocomplete gets in the way, it's painfully slow, something doesn't feel right about this:

![autocomplete chrome](https://cloud.githubusercontent.com/assets/1091022/22400805/375ed606-e574-11e6-9daa-e5d6a63a5b27.gif)

is there a way to fix this?

**Comment by darwin** [comment]
How is this related to cljs-devtools? AFAIK cljs-devtools should not affect auto-completion in DevTools. This looks to me as a problem with DevTools itself or your project setup.
