### ISSUE TITLE
Make strings not seqable?

### ISSUE THREAD

**Issue by danielcompton** [binaryage/cljs-devtools#34]
I saw this in my devtools output today:

<img width="472" alt="screenshot of google chrome 16-02-17 10-51-45 am" src="https://cloud.githubusercontent.com/assets/811954/22997090/01b7fb06-f436-11e6-8170-7125361c4cf3.png">

Would it make sense to make strings not able to be expanded like that as a seq?

**Comment by darwin** [comment]
Strings are not expandable. I have just tested it using 0.9.1 with latest ClojureScript.

Two possible theories come to my mind:
1) you are using cljs-devtools 0.9.0 and latest ClojureScript, so you are missing [this commit](https://github.com/binaryage/cljs-devtools/commit/3267356be0d2d5d4084191f104cb80c239d2f6b6).
2) That `:selected-brief` thing looks like a kind of GUID type, which behaves like string but implements `ISequable` on top.

**Comment by danielcompton** [comment]
This was using cljs-devtools 0.9.0, updating to 0.9.1 fixed it. Sorry!
