### ISSUE TITLE
Override re-frame-trace styles on a per call level

### ISSUE THREAD

**Issue by danielcompton** [binaryage/cljs-devtools#39]
We're using this very useful library as part of [re-frame-trace](https://github.com/Day8/re-frame-trace). It would be helpful to be able to set the styling at a per API call level so that we don't overwrite anyone else's config that they're using in the console.

**Comment by darwin** [comment]
I think you can easily swap effective prefs just before you call into cljs-devtools API.

See:
https://github.com/binaryage/cljs-devtools/blob/master/src/lib/devtools/prefs.cljs#L15

You can wrap your code here[1] with something like:
```
(binding [devtools.prefs/*current-config* trace-config]
  ...)
```
Or use `set-prefs!` / `get-prefs` API in try-finally (recommended).

[1] https://github.com/Day8/re-frame-trace/blob/4935d3f/src/day8/re_frame/trace/app_db.cljs#L43

**Comment by darwin** [comment]
https://github.com/darwin/re-frame-trace/commit/cf81870e13de01235eac576409c9381ce2c5cb7c
