### ISSUE TITLE
Mori integration

### ISSUE THREAD

**Issue by roman01la** [binaryage/cljs-devtools#4]
Is it possible to use somehow with [mori](https://github.com/swannodette/mori)?

**Comment by darwin** [comment]
Yes, but right now you have build mori in dev mode. I wasn't able to make it work with release version of mori.

Follow this issue and branch linked there:
https://github.com/swannodette/mori/issues/144

**Comment by roman01la** [comment]
I see. I've been reading you [ticket](http://dev.clojure.org/jira/browse/CLJS-1249) and I agree, everyone is using mori's prod bundle.

Probably the formatter could be re-written in JS? Without it, I'm still happy to do just `mori.toJs(x);`.

**Comment by darwin** [comment]
I'm not going to implement cljs-devtools in plain javascript. That is for sure.

I believe this problem will go away in the future. More people using ClojureScript will point out that bug and it will get fixed upstream eventually. For now we have to wait.

**Comment by roman01la** [comment]
:+1:

**Comment by roman01la** [comment]
I've managed to build something less fancy in JS. In case someone is also looking for this to work with mori, try [mori-devtools](https://github.com/roman01la/mori-devtools).

**Comment by darwin** [comment]
Nice! Custom formatters are fun. I look forward to see other uses in the wild.

**Comment by darwin** [comment]
I'm going to close this ticket. I'm not going to build mori version at this point.
