### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by olieidel** [binaryage/cljs-devtools#40]
Firefox is gaining popularity since the Quantum release. I'm wondering what the best approach for implementing cljs-devtools in Firefox would be:

- Creating an entire separate project for cljs-devtools for Firefox as this project currently is Chrome-only
- Or: Add support for Firefox to this project.

I'm happy to give this a try once a sketch for a way forward is made. And thank you so much for your work in cljs-devtools, it's super awesome!

**Comment by darwin** [comment]
I would not be against adding Firefox support to this project. The code could dynamically detect browser environment and act accordingly. That would be convenient from library user stand point. Also a lot of code could be shared. 

But personally I'm not going to implement it and maintain it. I personally use Chrome for development and I'm not going to switch anytime soon. And I'm saying this as someone who made quite some work on [Firebug extensions back in the day](https://www.binaryage.com/unsupported).

**Comment by olieidel** [comment]
Thanks for your reply!
Alright, so for now I suppose I'll create a separate repository and we'll see how it goes from there.

**Comment by hkjels** [comment]
@olieidel have you made any progress with this?

**Comment by olieidel** [comment]
Nope, last I checked Firefox is actually missing the needed APIs for this. Feel free to look into it again as my knowledge may be outdated :)

**Comment by royalaid** [comment]
Per [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1262914) bugzilla issue it is just in the backlog, maybe post for demand for this kind of thing there?
