### ISSUE TITLE
Formatting values in Debugger and React Dev Tools 

### ISSUE THREAD

**Issue by DjebbZ** [binaryage/cljs-devtools#45]
Hello,

Just an idea: when stepping through the debugger, the values printed inline are not the nicely output values of cljs-devtools. Same when using React Dev Tools, the "props", "state" etc. aren't. It would be super cool if they were.

I'm almost sure it's a limitation of Chromium itself for not exposing the necessary APIs/hooks, but I just wanted to make it sure here before.

Thanks for your work by the way, I include in every CLJS project I use :)

**Comment by darwin** [comment]
It is not possible to implement this in a library. A modification of Chrome DevTools is needed.

btw. I've implemented this in [Dirac](https://github.com/binaryage/dirac).

**Comment by DjebbZ** [comment]
This is the response I excepted. I've read Dirac documentation and indeed, can't be done without changes in DevTools themselves.

Thank you for your fast and precise answer!
