### ISSUE TITLE
Any way to customize formatting?

### ISSUE THREAD

**Issue by tslocke** [binaryage/cljs-devtools#46]
For example, map entries are elided after the first 5. This often causes very busy logging in my app. I'd like to be able to change it to 3. There's various things like that I'd like to do if it wasn't too difficult.

Is there any way to hook into this stuff?

Thanks very much for this project. So useful!

**Comment by darwin** [comment]
Pretty much anything is customizable. Look here:
https://github.com/binaryage/cljs-devtools/blob/master/src/lib/devtools/defaults.cljs

But you will have to dig a bit in the code to figure out what individual options affect. No docs, sorry.
