### ISSUE TITLE
println

### ISSUE THREAD

**Issue by atroche** [binaryage/cljs-devtools#5]
Is there a way of getting this to work with `println` instead of just with the native console.log (or macros that compile down to it)?

**Comment by darwin** [comment]
I don't see how this could be related to println. cljs-devtools wraps functionality exposed by Chrome's devtools. There is no similar functionality in terminals (or other targets of println).

Or do you want your printlns to call console.log under the hood?

**Comment by atroche** [comment]
Yeah, sorry for the confusion! I've been using enable-console-print! for so
long that I'd forgotten other people don't use it... It makes println use
console.log, but unfortunately in a way that wrecks devtools formatting (I
think it converts it to JS first).

**Comment by darwin** [comment]
It is no mystery. The println and similar printing functions produce a string which is then passed to `*print-fn*` (which is implemented by enable-console-print! using console.log):

https://github.com/clojure/clojurescript/blob/2677ff7a595e872d9393237818894d84a0214083/src/main/cljs/cljs/core.cljs#L141-L151

So devtools see only strings, not original data structures.

If you want println to behave like console.log, you have to :exclude standard cljs.core implementation and implement your own, which would pass all args to console.log *as-is*.
