### ISSUE TITLE
GET http://localhost:9500/null 404 (Not Found) @ hints.cljs:62

### ISSUE THREAD

**Issue by oskarkv** [binaryage/cljs-devtools#50]
I'm trying to install cljs-devtools for the first time. If I do `(devtools.core/install! [:formatters :hints])` and then try to evaluate something which gives an error, like just calling a function that does not exist, I get an error:

`GET http://localhost:9500/null 404 (Not Found)  @ hints.cljs:62`

Did I do something wrong? I added devtools as a dependency in deps.edn. I'm using figwheel-main, and it installs formatters, but I haven't yet figured out how to get it to install :hints too automatically. I added ` :external-config {:devtools/config {:features-to-install [:formatters :hints]}}}` in my figwheel-main `dev.cljs.edn` file, but when checking with `(devtools.core/installed? :hints)` it's false. So I did `install!` as above and got the error.

The full stack trace is:

devtools$hints$ajax_reader @ hints.cljs:62
devtools$hints$retrieve_javascript_source @ hints.cljs:67
devtools$hints$mark_null_call_site_location @ hints.cljs:88
devtools$hints$make_sense_of_the_error @ hints.cljs:97
devtools$hints$error_object_sense @ hints.cljs:109
devtools$hints$type_error_to_string @ hints.cljs:118
(anonymous) @ hints.cljs:136
(anonymous) @ core.cljs:2963
cljs$core$pr_writer_impl @ core.cljs:10174
cljs$core$pr_writer @ core.cljs:10183
cljs$core$pr_seq_writer @ core.cljs:10186
cljs$core$pr_sb_with_opts @ core.cljs:10194
cljs$core$pr_str_with_opts @ core.cljs:10204
(anonymous) @ core.cljs:10232
cljs$core$pr_str @ core.cljs:10229
figwheel$repl$eval_javascript_STAR__STAR_ @ repl.cljc:374
(anonymous) @ repl.cljc:384
G__13008__2 @ core.cljs:11039
G__13008 @ core.cljs:11025
(anonymous) @ repl.cljc:477
goog.events.EventTarget.fireListeners @ eventtarget.js:284
goog.events.EventTarget.dispatchEventInternal_ @ eventtarget.js:381
goog.events.EventTarget.dispatchEvent @ eventtarget.js:196
goog.net.WebSocket.onMessage_ @ websocket.js:426

**Comment by darwin** [comment]
Short answer: don't use hints feature in this case.

I don't think you did something wrong. The hints feature didn't resolve source file with your code properly and was unable to fetch it via `XMLHttpRequest`.

Looking at your stack trace it looks like you evaluated something in the REPL. AFAIK REPL has no on-disk source files associated and even if it had, it would likely not be visible through your web server.

More info:
https://github.com/binaryage/cljs-devtools/blob/master/docs/faq.md#what-is-the-hints-feature
https://github.com/binaryage/cljs-devtools/blob/master/src/lib/devtools/hints.cljs#L14-L35

**Comment by oskarkv** [comment]
Oh, right! If I don't eval something in the REPL it works. Thanks!

But do you know why `:hints` are not "installed" out of the box, even if I have `:external-config {:devtools/config {:features-to-install [:formatters :hints]}}}` in my `dev.cljs.edn`?

**Comment by darwin** [comment]
I don't know. I guess you need to debug it yourself.
