### ISSUE TITLE
Is devtools appending a line to js source?

### ISSUE THREAD

**Issue by oskarkv** [binaryage/cljs-devtools#51]
I'm not sure this is a cljs-devtools problem, so sorry if it's not. But I think it is, since it started happening when I installed cljs-devtools.

I found that my .js output files sometimes have a strange line appended to them. For exampe:
```
~/game(master) » tail -n 4 target/public/cljs-out/game/game/stats_and_items.js
});

//# sourceMappingURL=stats_and_items.js.map
and_items.js.map
```
That `and_items.js.map` should not be there, and is causing problems. Is this cljs-devtools' doing? Are you touching the .js files?

**Comment by darwin** [comment]
It is highly unlikely that cljs-devtools would be causing something like this.
