### ISSUE TITLE
Color scheme is hard to read in dark mode

### ISSUE THREAD

**Issue by simonacca** [binaryage/cljs-devtools#77]
First off, thank you so much for cljs-devtools, this is one of the key tools that make cljs development viable for me!

As can be seen in the image below, the chosen color scheme doesn't play well with the chrome devtools dark mode:
![image](https://github.com/binaryage/cljs-devtools/assets/1206381/947233be-1bf5-4706-be87-5b6f38870ca5)

Would you be open to a pr to improve on this?

Cheers,
Simon

**Comment by darwin** [comment]
Hi Simon, ah I'm sorry for my late reply. Sure, I would accept such PR. Thanks a lot!

**Comment by chr15m** [comment]
@simonacca note there is a prior issue #30. Perhaps this one can be closed as duplicate?
