### ISSUE TITLE
Displaying a var errors with "too deep hierarchy"

### ISSUE THREAD

**Issue by jaredly** [binaryage/cljs-devtools#8]
![image](https://cloud.githubusercontent.com/assets/112170/12203742/ce483e98-b5ed-11e5-98d2-2cd9018eeffe.png)

to repro:
```clj
(js/console.log (var x))
```

**Comment by darwin** [comment]
Ah, I see. The problem is that the data structure provided has cycles.

cljs-devtools could attempt to detect it, but I don't think this has a high priority at this point. DevTools sanity checks reject such deep hierarchy.

**Comment by jaredly** [comment]
gotcha. I'm using cljs-devtools formatter outside of devtools, so I guess I'll have to do the check myself :/

**Comment by darwin** [comment]
Interesting, I'm quite curious where outside of devtools do you use it. You wrote your own rendering function for generated JSON-ML?

I will fix it eventually next week. After I release out first version of [Dirac](https://github.com/binaryage/dirac).

Anyways, if you want to get stab at it, go for it. Better to fix it in cljs-devtools where the trouble is.

**Comment by jaredly** [comment]
Yup, jsonml is really close to hiccup, and I'm using reagent. Here's the place I'm using it (an in-browser REPL) http://jaredforsyth.com/mark-tutorial/ the repl is the bottom-right box

**Comment by darwin** [comment]
Oh, you are using replumb for the REPL. Cool!
