### ISSUE TITLE
displaying a lazy value w/ errors fails entirely

### ISSUE THREAD

**Issue by jaredly** [binaryage/cljs-devtools#9]
if you try to `(js/console.log (mapcat identity (range 10)))`, it doesn't fail at call-time b/c the value is lazy. It only errors when cljs-devtools tries to show it (specifically the `header-api-call` function.
Currently I'm wrapping that in a try/catch, which might be the best way to do it. Do you think header-api-call should have the try/catch instead?

**Comment by darwin** [comment]
Hm. I don't see this as a problem. This is standard behaviour of lazy sequences that they fail when realised. Where-ever it could be.

I'm not sure what `header-api-call` should do in case of such exception. I think such exception definitely should not be swallowed in exchange for some console error message.

I'm not sure about your use-case but wrapping it yourself sounds like the best approach to me. You can implement your own logging macro which could do it transparently.

**Comment by jaredly** [comment]
sounds good. I'm fine w/ it doing what it does
